language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
    fast_finish: true
    allow_failures:
        - php: 5.4

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer self-update

install:
    - composer install --optimize-autoloader --no-interaction --ignore-platform-reqs

script:
    - php vendor/bin/phpunit
    - php vendor/bin/behat --format progress
